---
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates for ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "ubuntu"

- hosts: Ubuntu
  become: true
  roles:
    - Horizon
    - Cinder
    - Neutron
